#!/bin/bash

if [[ ! -d ~/.local/blender ]] ; then
    set -o pipefail
    curdir="$(pwd)"
    cd ~/.local
    page=$(curl https://www.blender.org/download/ | grep "href=" | sed "s/.*href=\"//g;s/\".*//g" \
          | grep "download/Blender" | grep linux)
    link=$(curl -L "$page" | sed "s/.*href=\"//g;s/\".*//g" | grep -e "^http.*tar.xz" | sort -R | head -n 1)
    wget "$link" -O blender.tar.xz 2>&1 | \
    sed -u 's/^[a-zA-Z\-].*//; s/.* \{1,2\}\([0-9]\{1,3\}\)%.*/\1\n#Downloading... \1%/; s/^20[0-9][0-9].*/#Done./' | \
    zenity --progress --percentage=0 --title=Download dialog --text="Please wait..." --auto-close --auto-kill
    tar -xf blender.tar.xz | zenity --progress --pulsate --text="Extracting" --no-cancel --auto-kill --auto-close
    rm -f blender.tar.xz
    mv blender* blender
    cd blender/*/python/lib/python*
    patch -p1 -N < /opt/blender-installer/blender-use-local-python3.patch
    cd "$curdir"
fi
exec ~/.local/blender/blender $@
